spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 10
    password: 123
  clusterNodes: localhost:7000,localhost:7001,localhost:7002
  commandTimeout: 1000
